# Example secret for S3 credentials
# Create this secret in the bardiup-system namespace
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: bardiup-system
type: Opaque
stringData:
  accessKeyId: "your-access-key-id"
  secretAccessKey: "your-secret-access-key"
